AWSTemplateFormatVersion: "2010-09-09"
Description: "ES2 machine for pbpMyAdmin"
Parameters:
  KeyName:
    Description: "Key Pair name"
    Type: "AWS::EC2::KeyPair::KeyName"
    Default: "webserver"
  VPC:
    Description: "Just select the one and only default VPC"
    Type: "AWS::EC2::VPC::Id"
    Default: "vpc-feb2a199"
    AllowedValues: ["vpc-feb2a199"]
  Subnet:
    Description: "Just select one of the available subnets"
    Type: "AWS::EC2::Subnet::Id"
    Default: "subnet-0a889651"
    AllowedValues: ["subnet-0a889651"]
  InstanceType:
    Description: Select one of the possible instance types'
    Type: String
    Default: "t2.micro"
    AllowedValues: ["t2.micro", "t2.small", "t2.medium"]
Resources:
  EC2Instance:
    Type: "AWS::EC2::Instance"
    Properties:
      InstanceType: "t2.micro"
      ImageId: "ami-0dbf5ea29a7fc7e05"
      SecurityGroupIds:
        - !Ref sgmycomputers
        - !Ref sgwebserversec
      KeyName: !Ref KeyName
      SubnetId: !Ref Subnet
      UserData:
        # From https://github.com/andrewpuch/phpmyadmin_connect_to_rds
        "Fn::Base64": !Sub |
          #!/bin/bash -xe
          apt-get update
          apt-get upgrade -y
          apt-get dist-upgrade -y
          apt-get autoremove -y
          apt-get install apache2 php7.0 php7.0-cli php7.0-fpm php7.0-gd php-ssh2 libapache2-mod-php7.0 php7.0-mcrypt mysql-server php7.0-mysql git unzip zip postfix php7.0-curl mailutils php7.0-json phpmyadmin -y
          php5enmod mcrypt
          echo 'Include /etc/phpmyadmin/apache.conf' >> /etc/apache2/sites-enabled/000-default.conf
          service apache2 restart
          echo '' >> /etc/phpmyadmin/config.inc.php
          echo $i++; >> /etc/phpmyadmin/config.inc.php
          echo $cfg['Servers'][$i]['verbose']       = 'Northwind'; >> /etc/phpmyadmin/config.inc.php
          echo $cfg['Servers'][$i]['host']          = 'northwind-1.cki39k1nxe6r.us-west-1.rds.amazonaws.com'; >> /etc/phpmyadmin/config.inc.php
          echo $cfg['Servers'][$i]['port']          = '3306'; >> /etc/phpmyadmin/config.inc.php
          echo $cfg['Servers'][$i]['socket']        = ''; >> /etc/phpmyadmin/config.inc.php
          echo $cfg['Servers'][$i]['connect_type']  = 'tcp'; >> /etc/phpmyadmin/config.inc.php
          echo $cfg['Servers'][$i]['extension']     = 'mysql'; >> /etc/phpmyadmin/config.inc.php
          echo $cfg['Servers'][$i]['compress']      = FALSE; >> /etc/phpmyadmin/config.inc.php
          echo $cfg['Servers'][$i]['auth_type']     = 'config'; >> /etc/phpmyadmin/config.inc.php
          echo $cfg['Servers'][$i]['user']          = 'bmacarthur'; >> /etc/phpmyadmin/config.inc.php
          echo $cfg['Servers'][$i]['password']      = 'phpmyadmin'; >> /etc/phpmyadmin/config.inc.php
          echo '' >> /etc/phpmyadmin/config.inc.php
          echo $i++; >> /etc/phpmyadmin/config.inc.php
          echo $cfg['Servers'][$i]['verbose']       = 'Corp Roster'; >> /etc/phpmyadmin/config.inc.php
          echo $cfg['Servers'][$i]['host']          = 'corp-roster.cki39k1nxe6r.us-west-1.rds.amazonaws.com'; >> /etc/phpmyadmin/config.inc.php
          echo $cfg['Servers'][$i]['port']          = '3306'; >> /etc/phpmyadmin/config.inc.php
          echo $cfg['Servers'][$i]['socket']        = ''; >> /etc/phpmyadmin/config.inc.php
          echo $cfg['Servers'][$i]['connect_type']  = 'tcp'; >> /etc/phpmyadmin/config.inc.php
          echo $cfg['Servers'][$i]['extension']     = 'mysql'; >> /etc/phpmyadmin/config.inc.php
          echo $cfg['Servers'][$i]['compress']      = FALSE; >> /etc/phpmyadmin/config.inc.php
          echo $cfg['Servers'][$i]['auth_type']     = 'config'; >> /etc/phpmyadmin/config.inc.php
          echo $cfg['Servers'][$i]['user']          = 'admin'; >> /etc/phpmyadmin/config.inc.php
          echo $cfg['Servers'][$i]['password']      = 'CorpRoster'; >> /etc/phpmyadmin/config.inc.php
  sgmycomputers:
    Type: "AWS::EC2::SecurityGroup"
    Properties:
      GroupDescription: "Created by RDS management console"
      VpcId: !Ref VPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: "3306"
          ToPort: "3306"
          CidrIp: "0.0.0.0/0"
  sgwebserversec:
    Type: "AWS::EC2::SecurityGroup"
    Properties:
      GroupDescription: "webserver security"
      VpcId: !Ref VPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: "80"
          ToPort: "80"
          CidrIp: "0.0.0.0/0"
        - IpProtocol: tcp
          FromPort: "22"
          ToPort: "22"
          CidrIp: "0.0.0.0/0"
        - IpProtocol: tcp
          FromPort: "3306"
          ToPort: "3306"
          CidrIp: "0.0.0.0/0"
        - IpProtocol: tcp
          FromPort: "443"
          ToPort: "443"
          CidrIp: "0.0.0.0/0"
  Role:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: "ec2.amazonaws.com"
            Action:
              - "sts:AssumeRole"
      Policies:
        - PolicyName: ec2
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Sid: "1"
                Effect: Allow
                Action: "ec2:*"
                Resource: "*"
Outputs:
  ServerIP:
    Description: "Public IP address of the vpn server"
    Value: !GetAtt "EC2Instance.PublicIp"
